{pkgs, ...}: {
  home.shellAliases = {
    py = "nix develop $HOME/gh/micromamba/env";
    pt = "poetry -C ~/.cache/poetry";
    man = "${pkgs.bat-extras.batman}/bin/batman";
    rl = "exec zsh -l";
    rm = " rm -vdrf";
    cp = "cp -r";
    mkdir = " mkdir -p";
    l = "exa -al --across --icons -s age";
    ll = "exa -ahlg --across --icons -s age";
    lt = "l --tree";
    e = "$EDITOR";
    m = "amumax";
    op = "xdg-open";
    se = "sudoedit";
    tl = "zellij ls";
    ta = "zellij a -c";
    tk = "zellij k";
    rs = "rsync -rv";
    pm = "podman";
    cat = "bat -Pp";
    pmps = "pm ps -a --format \"table {{.Names}} {{.Status}} {{.Created}} {{.Image}}\"";
    sysu = "systemctl --user";
    cd = "z";
    d = "z";
    tldr = "tldr -q";
    ".." = "cd ..";
    "..." = "cd ../..";
    "...." = "cd ../../..";
    myip = "curl ifconfig.me";
    dev = "nix develop -c zsh";
    ghs = "gh copilot suggest -t shell";
    ghe = "gh copilot explain";
    ghc = "gh copilot";
    colors = "curl -Ls 'https://raw.githubusercontent.com/NNBnh/textart-collections/main/color/colortest.textart' | bash; echo";
    lg = "lazygit";
  };
}
